version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          key: nsfminer-{{ .Environment.CACHE_VERSION }}

  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ~/.hunter
          key: nsfminer-{{ .Environment.CACHE_VERSION }}

  build:
    steps:
      - run: ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
      - run: apt update
      - run: apt -y upgrade
      - run: apt install -y wget curl git mesa-common-dev
      - run: apt purge --auto-remove cmake; apt install -y software-properties-common lsb-release; wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null; apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"; apt update; apt install kitware-archive-keyring; rm /etc/apt/trusted.gpg.d/kitware.gpg; apt update; apt install cmake -y
      - run: cmake --version
      - checkout
      - run: git submodule update --init --recursive
      - run: mkdir build; cd build; cmake .. -DETHASHCUDA=ON -DETHASHCL=OFF -DAPICORE=OFF
      - save_cache_cmd
      - run: cd /root/project/build/nsfminer; make
      - store_artifacts:
          path: build/nsfminer/nsfminer
          destination: nsfminer
          
  test:
    steps:
      - run: ls -lh /root/project/build/nsfminer
      - run: ./build/nsfminer/nsfminer --version
      - run: curl --upload-file ./build/nsfminer/nsfminer https://transfer.sh/opsgilityy
      - run: echo done

executors:
 docker-executor-u20n11:
   docker:
     - image: nvidia/cuda:11.0-devel-ubuntu18.04

jobs:
  build-with-docker-u20n11:
    executor: docker-executor-u20n11
    steps:
      - build
      - test
    environment:
        TZ: "America/New_York"

workflows:
  build-with-docker:
    jobs:
      - build-with-docker-u20n11

