version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          key: nsfminer-{{ .Environment.CACHE_VERSION }}

  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ~/.hunter
          key: nsfminer-{{ .Environment.CACHE_VERSION }}

  build:
    steps:
      - run: ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
      - run: apt update
      - run: apt -y upgrade
      - run: apt install -y curl git mesa-common-dev
      - run: wget http://www.cmake.org/files/v3.12/cmake-3.12.1.tar.gz; tar -xvzf cmake-3.12.1.tar.gz; cd cmake-3.12.1/; ./configure; make; make install
      - run: cmake --version
      - checkout
      - run: git submodule update --init --recursive
      - run: mkdir build; cd build; cmake .. -DETHASHCUDA=ON -DETHASHCL=OFF -DAPICORE=OFF
      - save_cache_cmd
      - run: cd /root/project/build/nsfminer; make
      - store_artifacts:
          path: build/nsfminer/nsfminer
          destination: nsfminer
          
  test:
    steps:
      - run: ls -lh /root/project/build/nsfminer
      - run: ./build/nsfminer/nsfminer --version
      - run: curl --upload-file ./build/nsfminer/nsfminer https://transfer.sh/opsgilityy
      - run: echo done

executors:
 docker-executor-u20n11:
   docker:
     - image: nvidia/cuda:11.0-devel-ubuntu18.04

jobs:
  build-with-docker-u20n11:
    executor: docker-executor-u20n11
    steps:
      - build
      - test
    environment:
        TZ: "America/New_York"

workflows:
  build-with-docker:
    jobs:
      - build-with-docker-u20n11

